CREATE TABLE stackpilot.agent_telemetry (
    agent_id uuid PRIMARY KEY REFERENCES stackpilot.agents(id) ON DELETE CASCADE,
    cpu_usage_basis_points integer NOT NULL,
    memory_total_bytes bigint NOT NULL,
    memory_used_bytes bigint NOT NULL,
    memory_available_bytes bigint NOT NULL,
    load_1m_milli bigint NOT NULL,
    load_5m_milli bigint NOT NULL,
    load_15m_milli bigint NOT NULL,
    root_filesystem_total_bytes bigint NOT NULL,
    root_filesystem_used_bytes bigint NOT NULL,
    root_filesystem_available_bytes bigint NOT NULL,
    network_receive_bytes_total bigint NOT NULL,
    network_transmit_bytes_total bigint NOT NULL,
    uptime_seconds bigint NOT NULL,
    sample_window_ms bigint NOT NULL,
    reported_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT agent_telemetry_cpu_usage_basis_points_check CHECK (cpu_usage_basis_points >= 0 AND cpu_usage_basis_points <= 10000),
    CONSTRAINT agent_telemetry_memory_total_bytes_check CHECK (memory_total_bytes > 0),
    CONSTRAINT agent_telemetry_memory_available_bytes_check CHECK (memory_available_bytes >= 0 AND memory_available_bytes <= memory_total_bytes),
    CONSTRAINT agent_telemetry_memory_used_bytes_check CHECK (memory_used_bytes >= 0 AND memory_used_bytes = memory_total_bytes - memory_available_bytes),
    CONSTRAINT agent_telemetry_load_1m_milli_check CHECK (load_1m_milli >= 0),
    CONSTRAINT agent_telemetry_load_5m_milli_check CHECK (load_5m_milli >= 0),
    CONSTRAINT agent_telemetry_load_15m_milli_check CHECK (load_15m_milli >= 0),
    CONSTRAINT agent_telemetry_root_filesystem_total_bytes_check CHECK (root_filesystem_total_bytes > 0),
    CONSTRAINT agent_telemetry_root_filesystem_used_bytes_check CHECK (root_filesystem_used_bytes >= 0 AND root_filesystem_used_bytes <= root_filesystem_total_bytes),
    CONSTRAINT agent_telemetry_root_filesystem_available_bytes_check CHECK (root_filesystem_available_bytes >= 0 AND root_filesystem_available_bytes <= root_filesystem_total_bytes - root_filesystem_used_bytes),
    CONSTRAINT agent_telemetry_network_receive_bytes_total_check CHECK (network_receive_bytes_total >= 0),
    CONSTRAINT agent_telemetry_network_transmit_bytes_total_check CHECK (network_transmit_bytes_total >= 0),
    CONSTRAINT agent_telemetry_uptime_seconds_check CHECK (uptime_seconds >= 0),
    CONSTRAINT agent_telemetry_sample_window_ms_check CHECK (sample_window_ms >= 1 AND sample_window_ms <= 300000)
);
---- create above / drop below ----
DROP TABLE stackpilot.agent_telemetry;
